services:
  mysql:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3316:3306
    container_name: nukak-mysql-9

  mariadb:
    image: mariadb:11.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3326:3306
    container_name: nukak-mariadb-11

  postgres:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5442:5432
    container_name: nukak-postgres-18
