services:
  mysql:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3316:3306
    container_name: nukak-mysql-9
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mariadb:
    image: mariadb:11.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3326:3306
    container_name: nukak-mariadb-11
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5442:5432
    container_name: nukak-postgres-18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 5s
      retries: 10
